FROM python:3.11-slim

WORKDIR /app

COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api/ ./api/
COPY ../trained_models/ ./trained_models/

ENV PYTHONUNBUFFERED=1

EXPOSE 5000
CMD ["python", "api/app.py"]
